[package]
name = "apollo"
version = "0.1.0"
authors = ["csboo <csongiboo@gmail.com>", "Jeromos Kovacs <iitsnotme214@proton.me>"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chacha20poly1305 = { version = "0.10.1", optional = true }
ciborium = "0.2.2"
dioxus = { version = "0.7.2", features = ["fullstack"] }
# note: argon2 crate worth bearing in mind
rust-argon2 = { version = "3.0.0", optional = true }
secrecy = { version = "0.10.3", optional = true }
tokio = { version = "1.48.0", optional = true }

[features]
default = ["web"]
web = ["dioxus/web"]
desktop = ["dioxus/desktop"]
mobile = ["dioxus/mobile"]
server = ["dioxus/server", "dep:tokio", "dep:secrecy"]
# save server state
server_state_save = ["dep:chacha20poly1305", "dep:rust-argon2"]
