[package]
name = "apollo"
version = "0.1.0"
authors = ["csboo <csongiboo@gmail.com>", "Jeromos Kovacs <iitsnotme214@proton.me>"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ciborium = "0.2.2"
dioxus = { version = "0.7.2", features = ["fullstack"] }
tokio = { version = "1.48.0", optional = true }

[features]
default = ["web"]
web = ["dioxus/web"]
desktop = ["dioxus/desktop"]
mobile = ["dioxus/mobile"]
server = ["dioxus/server", "dep:tokio"]
